name: Deploy to Firebase
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: yarn run deploy
        working-directory: functions
  deploy_rules:
    runs-on: ubuntu-latest
    steps:
      - run: firebase deploy --only firestore:rules
